baseURL = "http://nickbom.github.io/"
languageCode = "en-us"
title = "Nicolas Bontempo"
subtitle = "Código, analise de dados, backend e outras curiosidades do mundo de TI."
theme = "hugo-paper"
[params]
  author = "Nicolas Bontempo"
  description = "Código, analise de dados, backend e outras curiosidades do mundo de TI."
[menu]
  [[menu.main]]
    name = "Linkedin"
    pre = "<i class='fa fa-road'></i>"
    url = "https://www.linkedin.com/in/nicolasbontempo"
  [[menu.main]]
    name = "Github"
    pre = "<i class='fa fa-road'></i>"
    url = "https://github.com/nickbom"
  [[menu.main]]
    identifier = "about"
    name = "Sobre o autor"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5